### ISSUE TITLE
Pretokenize file error

### ISSUE THREAD

**Issue by kunwar-vikrant** [xiscoding/utils#1]
while using the run_with_text options , it is unable to find the pretokenize function. Can you provide with the file required for the same pls.
```
pretokenize.py': [Errno 2] No such file or directory
unrecognized arguments: ""
9900
6414
27258
23360
23285
18015
16027
17317
10118
16743
6878
30512
29256
26781
2943
30278
```

can you provide the steps to run it with prompts ..

**Comment by xiscoding** [comment]
I am using the original version of this (https://github.com/karpathy/llama2.c.git) repo. When did you clone the llama2.c repo? The new version no longer includes the run_wrap file and the pretokenize file may have changed.

**Comment by kunwar-vikrant** [comment]
I am using the latest repo actually ......seems like there is no pretokenize file there instead it is a method defined under tokenizer.py..........are you able to run the model using an input prompt??

**Comment by xiscoding** [comment]
by default there is an option to use an input prompt with the original tiny stories dataset. The files in this utils folder do not work with the newest version of llama2.c you will need to clone the original version. I will update the code to work with the new version however since this is a baby model the results from training are pretty atrocious without training for an impractical amount of time. Make sure to read the documentation and clone my repo.

**Comment by kunwar-vikrant** [comment]
Got it, was able to get things to work.......but true that it requires insane amount of training on a single consumer hardware......Anyways thanks a ton for sharing ur work :)
