### ISSUE TITLE
Training BabyLLama on custom dataset

### ISSUE THREAD

**Issue by prp-e** [xiscoding/utils#2]
Hello. 
I guess you remember me from YouTube. I'm the person asking you to share the procedure of training Karpathy's baby llama project on a custom set of data.
Now I got enough time to spend on this cool project and your help is super appreciated.

**Comment by xiscoding** [comment]
Give me 1 - 2 weeks to finish up this first set of midterms. I am currently swamped with assignments. Still you can send me a general idea of what you are trying to do and if its simple I will point you in the right direction. The babyllama.c model/repo has been updated since I made this so a lot of the code wont work without reworking. I have not had time to do so. The gpt-llm-trainer is much better I would start there and change the messages to work with your use case.

**Comment by prp-e** [comment]
Well, sorry if I'm so late :) 
Is there still a chance?

**Comment by xiscoding** [comment]
I think your best bet would be to train llama2 (the biggest most official version you have) then convert the weights. Check the README [link](https://github.com/karpathy/llama2.c?tab=readme-ov-file#metas-llama-2-models). 

Llama is going to be json format similar to chatgpt. The baby models are going to want you to tokenize, chunk your data, etc.

I may need to update the gpt-llm-trainer repo, but if you go that route I should be doing a video on these things soon as well as updating/adding to repo(s).

**Comment by prp-e** [comment]
That would be cool. Any Links or resources on LLaMa 2 JSON formatting?

**Comment by xiscoding** [comment]
https://huggingface.co/blog/llama2#how-to-prompt-llama-2 

Then you can follow the json file in the document. Email me at xiscoding@gmail.com and we can look at what you have.
